### ISSUE TITLE
Cần update lại command lab cho wordpress

### ISSUE THREAD

**Issue by TrongTan124** [hocchudong/ghichep-docker#41]
https://github.com/hocchudong/ghichep-docker/blob/master/docs/docker-coban/docker-demo.md

Vì khởi tạo container wordpress không truyền tham số nên bị lỗi. Thực hiện chỉnh sửa lại câu lệnh chạy Lab cho wordpress như sau:

Tạo container Database:
```sh
docker run \
-e MYSQL_ROOT_PASSWORD=root \
-e MYSQL_USER=wpuser \
-e MYSQL_PASSWORD=vnptdata2017 \
-e MYSQL_DATABASE=wordpress_db \
--name wordpressdb -d mariadb
```

Tạo container wordpress:
```sh
docker run \
-e WORDPRESS_DB_USER=wpuser \
-e WORDPRESS_DB_PASSWORD=vnptdata2017 \
-e WORDPRESS_DB_NAME=wordpress_db \
-p 8082:80 \
--link wordpressdb:mysql \
--name wpcontainer1 -d wordpress
```

Truy cập từ ngoài vào thông qua địa chỉ: http://IP_HOST:8082

**Comment by congto** [comment]
@TrongTan124 ok
